trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  name: Default 
  demands:
    - agent.name -equals WIN-4G3TNA4VMUF  

stages:
- stage: ValidateComposeFile
  jobs:
  - job: Validate
    steps:
    - script: |
        docker-compose config
      displayName: 'Validate docker-compose.yml'

- stage: BuildAndTest
  dependsOn: ValidateComposeFile
  jobs:
  - job: Build
    steps:
    - task: DockerCompose@0
      inputs:
        action: 'Build services'
        dockerComposeFile: 'docker-compose.yml'
      displayName: 'Build Docker Services'
