# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   exclude:
     - '*'
pr:
 branches:
  include:
    - '*'
stages:
- stage: Build
  jobs:
  - job: PrintFile
  pool:
    name: Default 
    demands:
      - agent.name -equals WIN-4G3TNA4VMUF  
    steps:
    - powershell: |
        Write-Host "Creating a sample file"
        "Hello, Azure Pipelines!" | Out-File -FilePath print.txt
      displayName: 'Create a sample file'
      
    - powershell: |
        Write-Host "Printing the file contents"
        Get-Content -Path print.txt
      displayName: 'Print the file contents'

